services:
  bikeinfra:
    image: bikeinfra:latest
  nginx_dev:
    image: nginx
    ports:
      - 127.0.0.1:3333:3000
    volumes:
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - bikeinfra
