apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bi-storage
  namespace: ip-dashboard
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 16Gi
  storageClassName: cinderbronze
