apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  prod.conf: |
    server {
        listen       80;

        location /bicycle_infra/ {
            proxy_pass   http://bikeinfra.ip-dashboard.svc.cluster.local:80/;
        }

        location /bike_data/ {
            proxy_pass   http://bi-backend.ip-dashboard.svc.cluster.local:80/;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            # Prevent timeouts
            fastcgi_read_timeout        900;
            proxy_connect_timeout       900;
            proxy_send_timeout          900;
            proxy_read_timeout          900;
            send_timeout                900;

            # Ensure Django sees the correct script name
            proxy_set_header SCRIPT_NAME /bike_data;

            # Ensure trailing slashes are handled correctly
            rewrite ^/bike_data$ /bike_data/ permanent;
        }

        #location /bike_data/admin/ {
        #    return 404;
        #}
        #location /admin/ {
        #    return 404;
        #}

        location / {
            proxy_pass   http://frontend.ip-dashboard.svc.cluster.local:80/;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /_next/ {
            proxy_pass   http://frontend.ip-dashboard.svc.cluster.local:80/_next/;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

    }
