apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bikeinfra-storage
  namespace: ip-dashboard
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: cinderbronze
